Feature/pause on cancelled case
ONSdigital/census-fwmt-job-service-v4 pull request #184
Opened 2021-03-24 14:23 UTC by ocallaghanit

# Summary
[ ] Bug fix ( non-breaking change which fixes issue)
[x] New Feature ( non-breaking change which adds functionality )
[ ] Breaking Change (fix or feature that would cause existing functionality to change)

# Proposed Changes
Added pause cancel functionality 

# Checklist
- [ x] Unit Test written 
- [ ] Acceptance Tests updated
- [ ] Documentation Updated 
- [ ] Dependencies updated?  ( services, libraries)?
- [ ] SonarLint -  ( use the plugin )

# Additional Info
- How to demonstrate functionality  

# Screenshots

- Screen shot of Passed Unit/Acceptance Test

2021-03-24 14:29 UTC, JacobHarrisonONS approved these changes

2021-03-25 09:10 UTC, spdiaz1000 requested changes

2021-03-25 09:10 UTC, spdiaz1000 commented on src/main/java/uk/gov/ons/census/fwmt/jobservice/service/routing/hh/HHCancelledPause.java
> +          && (cache != null && cache.existsInFwmt && cache.lastActionInstruction.equals("Cancel"));
missing the address Level is U (I know its in the key fbut need to keep it consistenet)

2021-03-25 09:10 UTC, spdiaz1000 commented on src/main/java/uk/gov/ons/census/fwmt/jobservice/service/routing/hh/HhPause.java
> +          && (cache != null && cache.existsInFwmt && !cache.lastActionInstruction.equals("Cancel"));
oh it was missing here too! (The address level)

2021-03-25 16:53 UTC, spdiaz1000 approved these changes

2021-03-25 16:53 UTC, merged